# Generated by Django 5.0.7 on 2026-07-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='is_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reversed_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_transactions', to='inventory.stocktransaction'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
