# Generated by Django 5.0.7 on 2026-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('USER', 'User'), ('BUSINESS_OWNER', 'Business Owner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('ACCOUNTANT', 'Accountant')], default='USER', max_length=30),
        ),
    ]
