# Generated by Django 5.0.7 on 2026-07-02 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_employee_threads(apps, schema_editor):
    BusinessMember = apps.get_model('businesses', 'BusinessMember')
    SupportThread = apps.get_model('chat', 'SupportThread')
    for membership in BusinessMember.objects.filter(
        role='EMPLOYEE', status='ACTIVE', added_by__isnull=False,
    ):
        SupportThread.objects.get_or_create(
            thread_type='OWNER_EMPLOYEE',
            business_id=membership.business_id,
            owner_id=membership.added_by_id,
            member_id=membership.user_id,
            defaults={'created_by_id': membership.added_by_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_businessmember_added_by'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supportthread',
            name='unique_business_support_thread',
        ),
        migrations.AddField(
            model_name='supportthread',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_chat_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='thread_type',
            field=models.CharField(choices=[('PLATFORM', 'Platform Support'), ('OWNER_EMPLOYEE', 'Owner and Employee')], default='PLATFORM', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='supportthread',
            constraint=models.UniqueConstraint(condition=models.Q(('thread_type', 'PLATFORM')), fields=('business', 'member'), name='unique_platform_support_thread'),
        ),
        migrations.AddConstraint(
            model_name='supportthread',
            constraint=models.UniqueConstraint(condition=models.Q(('thread_type', 'OWNER_EMPLOYEE')), fields=('business', 'owner', 'member'), name='unique_owner_employee_thread'),
        ),
        migrations.RunPython(create_existing_employee_threads, migrations.RunPython.noop),
    ]
