# Generated by Django 5.0.7 on 2026-07-02 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_owner_memberships(apps, schema_editor):
    Business = apps.get_model('businesses', 'Business')
    BusinessMember = apps.get_model('businesses', 'BusinessMember')

    BusinessMember.objects.bulk_create([
        BusinessMember(
            business_id=business.id,
            user_id=business.owner_id,
            role='OWNER',
            status='ACTIVE',
        )
        for business in Business.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_id', 'role', 'user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessmember',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='unique_business_member'),
        ),
        migrations.RunPython(create_owner_memberships, migrations.RunPython.noop),
    ]
