# Generated by Django 5.0.7 on 2026-07-02 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_employee_owners(apps, schema_editor):
    BusinessMember = apps.get_model('businesses', 'BusinessMember')
    for membership in BusinessMember.objects.filter(role='EMPLOYEE').select_related('business'):
        membership.added_by_id = membership.business.owner_id
        membership.save(update_fields=['added_by'])


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businessmember_businessmember_unique_business_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_business_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_employee_owners, migrations.RunPython.noop),
    ]
